# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9a3804c239bc165b6f517a4cdeba8020b19072d44990cfcaff7f74df4f6e87c36217b3d0a236e65c875a93dc05e2866356f9ace3cc119ac6bf51be5ae3d846f

test:
  secret_key_base: 06b860ce6f45112fc643b5ec434480499efb44cdec89b28d0a179491f6103b5d517d1ea806d1f61bb7281a23806a845efa4cb413994c9c1ee7a9f248aa5dfd9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
